workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

variables:
  SCANNER_HOST: "http://iac-scanner:8080"

stages:
  - scan

iac_security_scan:
  image: alpine:latest
  tags:
    - docker
  stage: scan
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  script:
    # HTTP 저장소로 변경하여 SSL 문제 우회
    - sed -i 's/https/http/g' /etc/apk/repositories
    - apk add --no-cache curl jq ca-certificates git
    
    # 타겟 브랜치 fetch
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

    # 1. 변경된 terraform 파일 경로 수집
    - |
      echo "#1 Retrieving changed terraform files"

      changed_files=$(git diff --name-only --diff-filter=AM \
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME...HEAD \
        | grep -E '\.tf$' || true)

      echo "✓ Changed terraform files:"
      echo "$changed_files"
    
      # .tf 파일 변경이 없으면 스캔 건너뛰기
      if [ -z "$changed_files" ]; then
        echo "✓ No .tf files changed in this MR"
        echo "✓ Skipping IaC security scan"
        exit 0
      fi
    
      # JSON 배열로 변환
      files_array=$(echo "$changed_files" | jq -R . | jq -s .)
    
      # 전체 페이로드 생성
      payload=$(jq -n \
        --arg project_id "$CI_PROJECT_ID" \
        --arg project_path "$CI_PROJECT_PATH" \
        --arg mr_iid "$CI_MERGE_REQUEST_IID" \
        --arg source_branch "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" \
        --arg mr_title "$CI_MERGE_REQUEST_TITLE" \
        --argjson file_paths "$files_array" \
        '{
          project_id: ($project_id | tonumber),
          project_path: $project_path,
          mr_iid: ($mr_iid | tonumber),
          source_branch: $source_branch,
          mr_title: $mr_title,
          file_paths: $file_paths
        }')
    
    # 2. IaC Scanner API로 전송
    - |
      echo "#2 Sending to IaC Scanner API"

      response=$(curl -s -w "\n%{http_code}" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-API-Secret: $IAC_SCANNER_SECRET" \
        -d "$payload" \
        "${SCANNER_HOST}/api/scan")
      
      http_code=$(echo "$response" | tail -n1)
      body=$(echo "$response" | sed '$d')
      
      echo "✓ HTTP Status: $http_code"
      echo "✓ Response: $body"
      
      if [ "$http_code" != "200" ]; then
        echo "⚠️ Failed to send payload to IaC Scanner API"
        exit 1
      fi
    
    # 3. 스캔 완료 확인 (5초에 한 번씩 polling, 최대 60초)
    - |
      echo "#3 Waiting for scan to complete"

      project_name=$(echo "$CI_PROJECT_PATH" | awk -F'/' '{print $NF}')
      max_wait=60
      waited=0
      file_ready=false
      
      while [ $waited -lt $max_wait ]; do
        # Excel 파일이 준비되었는지 확인 (HEAD 요청)
        response_code=$(curl -s -o /dev/null -w "%{http_code}" \
          --head \
          "${SCANNER_HOST}/api/scan-results?project=${project_name}&mr=${CI_MERGE_REQUEST_IID}")
        
        if [ "$response_code" = "200" ]; then
          echo "✓ Excel file is ready after ${waited}s"
          file_ready=true
          break
        fi
        
        sleep 5
        waited=$((waited + 5))
        echo "Waiting... ${waited}s (HTTP $response_code)"
      done
      
      if [ "$file_ready" = "false" ]; then
        echo "⚠️ Excel file not ready after ${max_wait}s"
        echo "This is expected if no .tf files were changed"
        exit 0
      fi
    
    # 4. 서버에서 Excel 파일 다운로드
    - |
      echo "#4 Downloading Excel file from IaC Scanner API"

      excel_filename="${project_name}_#${CI_MERGE_REQUEST_IID}.xlsx"
      response_code=$(curl -s -w "%{http_code}" \
        -o "${excel_filename}" \
        "${SCANNER_HOST}/api/scan-results?project=${project_name}&mr=${CI_MERGE_REQUEST_IID}")
      
      if [ "$response_code" = "200" ]; then
        echo "✓ Successfully downloaded Excel file"
        echo "File info:"
        ls -lah "${excel_filename}"
      else
        echo "⚠️ Failed to download Excel file (HTTP $response_code)"
        exit 1
      fi
    
    # 5. Excel 다운로드 성공 후 댓글 작성 (다운로드 링크 포함) -> 두 번째 댓글
    - |
      echo "#5 Posting download link comment to MR"
      
      # 파일명을 URL 인코딩 (# → %23)
      excel_filename_encoded=$(echo "${excel_filename}" | sed 's/#/%23/g')
      
      # Artifacts URL 생성
      # CI/CD 변수 사용 (GitLab이 자동으로 제공)
      # artifacts_url="http://localhost/${CI_PROJECT_PATH}/-/jobs/${CI_JOB_ID}/artifacts/file/${excel_filename_encoded}"
      artifacts_url="${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/${excel_filename_encoded}"
      
      # 댓글 작성 페이로드 생성
      comment_payload=$(jq -n \
        --arg project_path "$CI_PROJECT_PATH" \
        --arg mr_iid "$CI_MERGE_REQUEST_IID" \
        --arg artifacts_url "$artifacts_url" \
        --arg file_name "$excel_filename" \
        '{
          project_path: $project_path,
          mr_iid: ($mr_iid | tonumber),
          artifacts_url: $artifacts_url,
          file_name: $file_name
        }')
      
      # 서버 API로 댓글 작성 요청
      comment_response=$(curl -s -w "\n%{http_code}" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-API-Secret: $IAC_SCANNER_SECRET" \
        -d "$comment_payload" \
        "${SCANNER_HOST}/api/download-link")
      
      comment_http_code=$(echo "$comment_response" | tail -n1)
      comment_body=$(echo "$comment_response" | sed '$d')
      
      if [ "$comment_http_code" = "200" ]; then
        echo "✓ Successfully posted download link comment to MR"
      else
        echo "⚠️  Failed to post comment (HTTP $comment_http_code)"
      fi
  artifacts:
    name: "iac-scan-mr-$CI_MERGE_REQUEST_IID"
    paths:
      - "*.xlsx"
    expire_in: 30 days
    when: always